"""
Django settings for django_temporary_permissions project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

from ..config import env
from .fragments.constance import *  # noqa: F401,F403
from .fragments.ddt import *  # noqa: F401,F403
from .fragments.security import *  # noqa: F401,F403
from .fragments.sentry import *  # noqa: F401,F403
from .fragments.smartadmin import *  # noqa: F401,F403

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = (
    [
        "smart_env",
        # 'django.contrib.admin',  # replace by django-smart-admin
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django_celery_beat",
    ]
    + SMART_ADMIN_APPS  # noqa: F405
    + DDT_APPS  # noqa: F405 we import it from smartadmin fragment
    + [
        # Project apps.
        "django_temporary_permissions",
        "django_temporary_permissions.core",
        # Third party apps.
        "constance.apps.ConstanceConfig",
    ]
)

try:
    import django_extensions as _  # noqa: F401

    INSTALLED_APPS.append("django_extensions")
except ModuleNotFoundError:
    pass

MIDDLEWARE = (
    [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]
    + DDT_MIDDLEWARES  # noqa: F405
    + [
        # Third party middlewares.
    ]
)


ROOT_URLCONF = "django_temporary_permissions.config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "web/templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_temporary_permissions.config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL"),
}


DATABASES["default"]["OPTIONS"] = {"options": "-c search_path=django"}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

if DEBUG:
    AUTH_PASSWORD_VALIDATORS = []
else:
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = env.str("STATIC_ROOT")
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    # str(BASE_DIR / "web" / "static"),
]

MEDIA_ROOT = env("MEDIA_ROOT")
MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

ADMINS = env("ADMINS")
TEST_USERS = env("TEST_USERS")
ADMIN_PANEL_URL = env("ADMIN_PANEL_URL")
