# Generated by Django 5.2.5 on 2025-09-08 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_temporary_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertemporarypermission',
            options={'verbose_name': 'Temporary User Permission', 'verbose_name_plural': 'Temporary User Permissions'},
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this temporary permission was created'),
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='created_by',
            field=models.ForeignKey(help_text='User who granted this temporary permission', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='created_temporary_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='end_datetime',
            field=models.DateTimeField(help_text='Date and time when the permission expires'),
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this temporary permission', null=True),
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='permission',
            field=models.ForeignKey(help_text='The permission being granted temporarily',
                                    on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='start_datetime',
            field=models.DateTimeField(help_text='Date and time when the permission becomes active'),
        ),
        migrations.AlterField(
            model_name='usertemporarypermission',
            name='user',
            field=models.ForeignKey(help_text='User receiving the temporary permission',
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        )
    ]
