# Generated by Django 5.2.5 on 2025-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_temporary_permissions', '0002_update_help_text'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertemporarypermission',
            constraint=models.CheckConstraint(condition=models.Q(('end_datetime__gte', models.F('start_datetime'))),
                                              name='end_after_start'),
        ),
    ]
