# Generated by Django 5.2.6 on 2025-09-17 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_temporary_permissions", "0003_auto_20250908_1021"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertemporarypermission",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="usertemporarypermission",
            name="created_by",
        ),
    ]
