# Generated by Django 5.2.6 on 2025-09-17 16:52

import django_temporary_permissions.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_temporary_permissions", "0004_remove_usertemporarypermission_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertemporarypermission",
            name="end_datetime",
            field=models.DateTimeField(
                help_text="Date and time when the permission expires",
                validators=[django_temporary_permissions.validators.validate_date_not_in_past],
            ),
        ),
        migrations.AlterField(
            model_name="usertemporarypermission",
            name="notes",
            field=models.TextField(help_text="Optional notes about this temporary permission", null=True),
        ),
        migrations.AlterField(
            model_name="usertemporarypermission",
            name="start_datetime",
            field=models.DateTimeField(
                help_text="Date and time when the permission becomes active",
                validators=[django_temporary_permissions.validators.validate_date_not_in_past],
            ),
        ),
    ]
